//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MGR_Entidades.Entidad
{
    public partial class GRTA_DECLARACIONES_PERFIL
    {
        public GRTA_DECLARACIONES_PERFIL()
        {
            this.GRTA_MENSAJES_SUJETO = new HashSet<GRTA_MENSAJES_SUJETO>();
        }
    
        public long ID_PERFIL { get; set; }
        public Nullable<byte> SUJETO_RIESGO { get; set; }
        public string IDENTIFICADOR_DECLARACION { get; set; }
        public Nullable<int> TIPO_REQUERIMIENTO { get; set; }
        public Nullable<int> TIPO_MOMENTO { get; set; }
        public Nullable<bool> INDICADOR_ACTIVO { get; set; }
        public Nullable<int> SELECCION_CASOS { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<bool> INDICADOR_SELECCION { get; set; }
        public Nullable<System.DateTime> FECHA_DECLARACION { get; set; }
        public Nullable<int> CLASE_MEDIDA { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO_IDX { get; set; }
        public Nullable<int> TOTAL_LINEAS { get; set; }
        public Nullable<decimal> PERFIL_RIESGO { get; set; }
        public Nullable<int> GRADO_RIESGO { get; set; }
        public Nullable<int> TIPO_MOTIVO { get; set; }
        public string DESCRIPCION_MOTIVO { get; set; }
        public Nullable<System.DateTime> FECHA_MOTIVO { get; set; }
        public Nullable<int> SESSION_MOTIVO { get; set; }
    
        public virtual GRTA_SESSION GRTA_SESSION { get; set; }
        public virtual ICollection<GRTA_MENSAJES_SUJETO> GRTA_MENSAJES_SUJETO { get; set; }
    }
    
}
