//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MGR_Entidades.Entidad
{
    public partial class GRTA_USUARIO
    {
        public GRTA_USUARIO()
        {
            this.GRTA_USUARIO_PROPIEDAD = new HashSet<GRTA_USUARIO_PROPIEDAD>();
            this.GRTA_USUARIO_ROL = new HashSet<GRTA_USUARIO_ROL>();
            this.GRTA_USUARIO_FUNCIONALIDAD = new HashSet<GRTA_USUARIO_FUNCIONALIDAD>();
            this.GRTA_USUARIO_FUNC_OPERACION = new HashSet<GRTA_USUARIO_FUNC_OPERACION>();
        }
    
        public int ID_USUARIO { get; set; }
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string EMAIL { get; set; }
        public byte[] FOTO { get; set; }
        public decimal USUARIO_ADMINISTRADOR { get; set; }
        public decimal ESTADO { get; set; }
        public Nullable<System.DateTime> VIGENCIA_CLAVE { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_ELIMINACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ICollection<GRTA_USUARIO_PROPIEDAD> GRTA_USUARIO_PROPIEDAD { get; set; }
        public virtual ICollection<GRTA_USUARIO_ROL> GRTA_USUARIO_ROL { get; set; }
        public virtual ICollection<GRTA_USUARIO_FUNCIONALIDAD> GRTA_USUARIO_FUNCIONALIDAD { get; set; }
        public virtual ICollection<GRTA_USUARIO_FUNC_OPERACION> GRTA_USUARIO_FUNC_OPERACION { get; set; }
    }
    
}
