//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MGR_Entidades.Entidad
{
    public partial class GRTA_EVALUACION
    {
        public int ID_EVALUACION { get; set; }
        public Nullable<byte> SUJETO_RIESGO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ESTADO_EVALUACION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_ANALISIS { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_ANALISIS { get; set; }
        public Nullable<int> TOTAL_DOCUMENTOS { get; set; }
        public Nullable<int> CLASE_MEDIDA { get; set; }
    }
    
}
