//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MGR_Entidades.Entidad
{
    public partial class GRTA_SESSION
    {
        public GRTA_SESSION()
        {
            this.GRTA_DECLARACIONES_PERFIL = new HashSet<GRTA_DECLARACIONES_PERFIL>();
            this.GRTA_FUNCION_SUJETO = new HashSet<GRTA_FUNCION_SUJETO>();
            this.GRTA_MEDIDAS = new HashSet<GRTA_MEDIDAS>();
            this.GRTA_PARAMETROS = new HashSet<GRTA_PARAMETROS>();
            this.GRTA_VARIABLES = new HashSet<GRTA_VARIABLES>();
        }
    
        public int ID_SESSION { get; set; }
        public string CODIGO_USUARIO { get; set; }
        public string DIRECCION_IP { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string TOKEN { get; set; }
    
        public virtual ICollection<GRTA_DECLARACIONES_PERFIL> GRTA_DECLARACIONES_PERFIL { get; set; }
        public virtual ICollection<GRTA_FUNCION_SUJETO> GRTA_FUNCION_SUJETO { get; set; }
        public virtual ICollection<GRTA_MEDIDAS> GRTA_MEDIDAS { get; set; }
        public virtual ICollection<GRTA_PARAMETROS> GRTA_PARAMETROS { get; set; }
        public virtual ICollection<GRTA_VARIABLES> GRTA_VARIABLES { get; set; }
    }
    
}
