//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MGR_Entidades.Entidad
{
    public partial class GRTA_FUNCION_SUJETO
    {
        public byte SUJETO_RIESGO { get; set; }
        public int TIPO_MEDIDA { get; set; }
        public Nullable<int> TIPO_FUNCION { get; set; }
        public string FUNCION_ANALISIS { get; set; }
        public string FUNCION_PRODUCCION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<int> SESSION_REGISTRO { get; set; }
    
        public virtual GRTA_SESSION GRTA_SESSION { get; set; }
    }
    
}
