//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MGR_Entidades.Entidad
{
    public partial class GRTA_PARAMETROS
    {
        public short ID_PARAMETRO { get; set; }
        public Nullable<byte> SUJETO_RIESGO { get; set; }
        public Nullable<int> CLASE_PARAMETRO { get; set; }
        public string VALOR_SUMINISTRADO { get; set; }
        public Nullable<short> VALOR_CODIGO_VARIABLE { get; set; }
        public Nullable<short> VALOR_IDENTIFICACION_SUJETO { get; set; }
        public string DESCRIPCION_BREVE { get; set; }
        public Nullable<int> TIPO_DATO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<int> SESSION_REGISTRO { get; set; }
    
        public virtual GRTA_SESSION GRTA_SESSION { get; set; }
    }
    
}
