//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MGR_Entidades.Entidad
{
    public partial class GRTA_MEDIDAS
    {
        public GRTA_MEDIDAS()
        {
            this.GRTA_MENSAJES_SUJETO = new HashSet<GRTA_MENSAJES_SUJETO>();
        }
    
        public int ID_MEDIDA { get; set; }
        public byte VERSION_MEDIDA { get; set; }
        public Nullable<byte> SUJETO_RIESGO { get; set; }
        public Nullable<int> TIPO_MEDIDA { get; set; }
        public Nullable<int> CLASE_MEDIDA { get; set; }
        public Nullable<short> ID_POLITICA { get; set; }
        public Nullable<int> ESTADO_MEDIDA { get; set; }
        public Nullable<int> JERARQUIA_MEDIDA { get; set; }
        public string NOMBRE_MEDIDA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_ANALISIS { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_ANALISIS { get; set; }
        public Nullable<byte> VALOR_FRECUENCIA { get; set; }
        public Nullable<int> TIPO_FRECUENCIA { get; set; }
        public Nullable<byte> RITMO_APRENDIZAJE { get; set; }
        public Nullable<decimal> TERMINO_MOMENTO { get; set; }
        public Nullable<int> MEDIDA_PRECEDENTE { get; set; }
        public Nullable<byte> VERSION_PRECEDENTE { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<int> SESSION_REGISTRO { get; set; }
        public Nullable<int> FUNCION_ACTIVACION { get; set; }
        public Nullable<bool> FLAG_REPLICACION { get; set; }
    
        public virtual GRTA_MEDIDAS GRTA_MEDIDAS1 { get; set; }
        public virtual GRTA_MEDIDAS GRTA_MEDIDAS2 { get; set; }
        public virtual GRTA_SESSION GRTA_SESSION { get; set; }
        public virtual ICollection<GRTA_MENSAJES_SUJETO> GRTA_MENSAJES_SUJETO { get; set; }
    }
    
}
