//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MGR_Entidades.Entidad
{
    public partial class VW_COMPENDIO_SUJETO
    {
        public short COD_ { get; set; }
        public string NOMBRE_SUJETO { get; set; }
        public string TABLA_ { get; set; }
        public string ORIG_FUENTE { get; set; }
        public string TIP_TABLA { get; set; }
        public string FECHAS { get; set; }
        public short TABLAS_SUJETO { get; set; }
        public Nullable<byte> SUJETO_RIESGO { get; set; }
        public string NOMBRE_TABLA { get; set; }
        public string CODIGO_ALTERNO { get; set; }
        public Nullable<int> ORIGEN_FUENTE { get; set; }
        public Nullable<int> TIPO_TABLA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_VIGENCIA { get; set; }
        public string DESCRIPCION_BREVE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<short> ID_PARAMETRO { get; set; }
    }
    
}
