//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGR_Model
{
    using MGR_Entidades.Entidad;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelMGRContext : DbContext
    {
        public ModelMGRContext()
            : base("name=ModelMGRContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GRTA_SESSION> GRTA_SESSION { get; set; }
        public virtual DbSet<GRTA_DECLARACIONES_PERFIL> GRTA_DECLARACIONES_PERFIL { get; set; }
        public virtual DbSet<GRTA_EVALUACION> GRTA_EVALUACION { get; set; }
        public virtual DbSet<GRTA_FUNCION_SUJETO> GRTA_FUNCION_SUJETO { get; set; }
        public virtual DbSet<GRTA_MEDIDAS> GRTA_MEDIDAS { get; set; }
        public virtual DbSet<GRTA_MENSAJES_SUJETO> GRTA_MENSAJES_SUJETO { get; set; }
        public virtual DbSet<GRTA_PARAMETROS> GRTA_PARAMETROS { get; set; }
        public virtual DbSet<GRTA_VARIABLES> GRTA_VARIABLES { get; set; }
        public virtual DbSet<VW_COMPENDIO_SUJETO> VW_COMPENDIO_SUJETO { get; set; }
        public virtual DbSet<GRTA_USUARIO_FUNC_OPERACION> GRTA_USUARIO_FUNC_OPERACION { get; set; }
        public virtual DbSet<GRTA_USUARIO_FUNCIONALIDAD> GRTA_USUARIO_FUNCIONALIDAD { get; set; }
        public virtual DbSet<GRTA_USUARIO_PROPIEDAD> GRTA_USUARIO_PROPIEDAD { get; set; }
        public virtual DbSet<GRTA_USUARIO_ROL> GRTA_USUARIO_ROL { get; set; }
        public virtual DbSet<GRTA_USUARIO> GRTA_USUARIO { get; set; }
    }
}
